import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div className="ml-16">
      <Head>
        <title>TechNote</title>
        <meta
          name="Your coding notes for Python, Javascript and more"
          content="Generated by create next app"
        />
      </Head>

      <main>
        <Sidebar />
        <h1
          className="text-center font-bold text-3xl p-10 
          text-stone-900"
        >
          Welcome to TechNote
        </h1>
        <div className="">
          <section>
            <h1 className="h1">Importing Data</h1>
            <h2 className="h2">Importing CSV Files</h2>
            <div className="codeSection">
              <code className="">
                <div className="h2code">import pandas as pd</div>
                <div className="h2code">
                  pd.read_csv(&apos;fileName.csv&apos;)
                </div>
              </code>
            </div>
            <p className="h2p">
              The pd stands for the Pandas library which we have just imported.
              The use of the variable pd is arbitrary, however we will follow
              the convention of using pd.
            </p>
            <h2 className="h3">
              Importing a CSV File Saved in a Different Folder Location
            </h2>
            <div className="codeSection">
              <code className="">
                <div className="h3code">import pandas as pd</div>
                <div className="h3code">
                  pd.read_csv(r&apos;/Users/UserName/fileName.csv&apos;)
                </div>
              </code>
            </div>
            <p className="h3p">
              The r stands for raw and it causes backslashes to be interpreted
              as regular text rather than as special characters. It is only
              necessary when we use backslashes, however we included this in our
              example just to avoid confusion.
            </p>
            <h2 className="h3">Specify a Header Row</h2>
            <div className="codeSection">
              <code className="">
                <div className="h3code">import pandas as pd</div>
                <div className="h3code">
                  pd.read_csv(&apos;fileName.csv&apos;, header=1)
                </div>
              </code>
              <p className="h3p">
                In our example dataset, the first row is already our header row,
                so it’s not necessary to indicate the parameter and argument
                header = 0. If the first row of our dataset appeared on the
                third row, we can use header = 2. I have encountered this in
                most reports generated using some reporting software like
                Business Objects or Excel data downloaded from Bloomberg.
              </p>
            </div>
            <h2 className="h2">Importing Excel Files</h2>
            <div className="codeSection">
              <code className="">
                <div className="h2code">import pandas as pd</div>
                <div className="h2code">
                  pd.read_excel(&apos;fileName.xlsxv)
                </div>
              </code>
            </div>
            <h2 className="h2">
              Importing an Excel File Saved in a Different Folder Location
            </h2>
            <div className="codeSection">
              <code className="">
                <div className="h2code">import pandas as pd</div>
                <div className="h2code">
                  pd.read_excel(r&apos;/Users/UserName/fileName.xlsx&apos;)
                </div>
              </code>
            </div>
            <h2 className="h2">Using a Variable File Path</h2>
            <div className="codeSection">
              <code className="">
                <div className="h2code">import os</div>
                <div className="h2code">
                  filePath = r&apos;/Users/UserName/fileName.csv&apos;
                </div>
                <div className="h2code">
                  fileName = &apos;fileName.csv&apos;
                </div>
                <div className="h2code">
                  directory = os.path.join(filePath,fileName)
                </div>
              </code>
            </div>
            <h2 className="h2">Adding Folders to a Variable File Path</h2>
            <div className="codeSection">
              <code className="">
                <div className="h2code">import os</div>
                <div className="h2code">
                  filePath = r&apos;/Users/UserName/fileName.csv&apos;
                </div>
                <div className="h2code">folderName = &apos;myFolder&apos;</div>
                <div className="h2code">
                  fileName = &apos;fileName.csv&apos;
                </div>
                <div className="h2code">
                  directory = os.path.join(filePath,folderName,fileName)
                </div>
              </code>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
